# Generated by Django 4.0.6 on 2022-07-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('prod_and_cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproductorder',
            name='shopproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_product_orders_tw', to='prod_and_cat.shopproduct'),
        ),
    ]
